import {Project, VariableDeclarationKind} from 'ts-morph';
import * as path from 'path';

export class TokenGenerator {
    private project: Project;

    constructor(project: Project) {
        this.project = project;
    }

    generate(outputDir: string): void {
        const tokensDir = path.join(outputDir, 'tokens');
        const filePath = path.join(tokensDir, 'index.ts');

        const sourceFile = this.project.createSourceFile(filePath, '', {overwrite: true});

        /*        sourceFile.addText(`/!**
         * Generated injection tokens
         * Do not edit this file manually
         *!/

        `);*/

        sourceFile.addImportDeclaration({
            namedImports: ['InjectionToken'],
            moduleSpecifier: '@angular/core',
        });
        sourceFile.addVariableStatement({
            isExported: true,
            declarationKind: VariableDeclarationKind.Const,
            declarations: [{
                name: "BASE_PATH",
                initializer: `new InjectionToken<string>('BASE_PATH', {
  providedIn: 'root',
  factory: () => '/api', // Default fallback
})`
            }],
            leadingTrivia: `/**
 * Injection token for the base API path
 */\n`
        });

        sourceFile.saveSync();
    }
}