/**
 * Header comments prepended to every generated file. All start with the
 * lint/format/typecheck-suppression pragmas: generated code must not fail a
 * consumer's stricter tooling (the compile-check suite strips @ts-nocheck and
 * asserts the output is strict-clean regardless).
 */
const disableLinting = `// @ts-nocheck\n/* eslint-disable */\n/* @noformat */\n/* @formatter:off */\n`;
const authorComment = `/**\n* Generated by ng-openapi\n`;
const defaultHeaderComment = disableLinting + authorComment;
export const TYPE_GENERATOR_HEADER_COMMENT =
    defaultHeaderComment +
    `* Generated TypeScript interfaces from Swagger specification\n* Do not edit this file manually\n*/\n`;
export const SERVICE_INDEX_GENERATOR_HEADER_COMMENT =
    defaultHeaderComment + `* Generated service exports\n* Do not edit this file manually\n*/\n`;
export const SERVICE_GENERATOR_HEADER_COMMENT = (controllerName: string) =>
    defaultHeaderComment +
    `* Generated Angular service for ${controllerName} controller\n* Do not edit this file manually\n*/\n`;
export const REQUEST_PARAMS_GENERATOR_HEADER_COMMENT =
    defaultHeaderComment + `* Generated request parameter interfaces\n* Do not edit this file manually\n*/\n`;
export const MAIN_INDEX_GENERATOR_HEADER_COMMENT =
    defaultHeaderComment + `* Entrypoint for the client\n* Do not edit this file manually\n*/\n`;
export const PROVIDER_GENERATOR_HEADER_COMMENT =
    defaultHeaderComment + `* Generated provider functions for easy setup\n* Do not edit this file manually\n*/\n`;
export const BASE_INTERCEPTOR_HEADER_COMMENT = (clientName: string) =>
    defaultHeaderComment +
    `* Generated Base Interceptor for client ${clientName}\n* Do not edit this file manually\n*/\n`;
export const HTTP_RESOURCE_GENERATOR_HEADER_COMMENT = (resourceName: string) =>
    defaultHeaderComment +
    `* Generated Angular \`httpResource\` service for ${resourceName}\n* Do not edit this file manually\n*/\n`;
export const ZOD_PLUGIN_GENERATOR_HEADER_COMMENT = (validatorName: string) =>
    defaultHeaderComment + `* Generated Zod Schemas for ${validatorName}\n* Do not edit this file manually\n*/\n`;
export const ZOD_PLUGIN_INDEX_GENERATOR_HEADER_COMMENT =
    defaultHeaderComment + `* Generated Zod Schemas exports\n* Do not edit this file manually\n*/\n`;
