import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { afterAll, describe, expect, it } from "vitest";
import { generateFromConfig } from "ng-openapi";

/**
 * Schemas named like the fixed files under models/ ("Index", "RequestOptions",
 * "RequestParams") must not clobber them in per-type mode: a schema kebab-cased
 * to "index" would otherwise overwrite the barrel in place (duplicated header,
 * model declaration inside the barrel, self-referential export) — silently.
 * The registry unit tests cover the suffixing policy; this test pins that
 * generatePerType actually reserves the names.
 */
describe("per-type model generation with reserved-name schemas", () => {
    const root = join(process.cwd(), "tmp", "per-type-reserved-names");

    afterAll(() => {
        rmSync(root, { recursive: true, force: true });
    });

    it("suffixes schemas colliding with fixed file names instead of clobbering them", async () => {
        rmSync(root, { recursive: true, force: true });
        mkdirSync(root, { recursive: true });
        const specPath = join(root, "spec.json");
        writeFileSync(
            specPath,
            JSON.stringify({
                openapi: "3.0.0",
                info: { title: "reserved-names", version: "1" },
                paths: {},
                components: {
                    schemas: {
                        Order: { type: "object", properties: { id: { type: "string" } } },
                        Index: {
                            type: "object",
                            properties: { order: { $ref: "#/components/schemas/Order" } },
                        },
                        RequestParams: { type: "object", properties: { page: { type: "number" } } },
                    },
                },
            }),
        );

        const output = join(root, "out");
        const result = await generateFromConfig({
            input: specPath,
            output,
            options: {
                dateType: "string",
                enumStyle: "union",
                generateServices: false,
                modelFileStructure: "per-type",
            },
        });

        // The colliding schemas land in suffixed files, each with a warning
        expect(readFileSync(join(output, "models", "index-2.ts"), "utf8")).toContain("export interface Index");
        expect(readFileSync(join(output, "models", "request-params-2.ts"), "utf8")).toContain(
            "export interface RequestParams",
        );
        expect(result.warnings.filter((warning) => warning.includes('"index.ts"'))).toHaveLength(1);
        expect(result.warnings.filter((warning) => warning.includes('"request-params.ts"'))).toHaveLength(1);

        // The barrel stays a pure barrel: header + export lines only, no
        // self-referential export, and it re-exports the suffixed files
        const barrel = readFileSync(join(output, "models", "index.ts"), "utf8");
        const statements = barrel.split("\n").filter((line) => line.startsWith("export"));
        expect(statements).toContain('export * from "./index-2";');
        expect(statements).toContain('export * from "./request-params-2";');
        expect(statements).not.toContain('export * from "./index";');
        expect(barrel).not.toContain("export interface");
        // One header only — the in-place overwrite bug duplicated it
        expect(barrel.match(/Generated by ng-openapi/g)).toHaveLength(1);
    });
});
