// packages/plugins/zod/src/lib/zod-index.generator.ts
import { Project } from "ts-morph";
import * as fs from "fs";
import * as path from "path";
import { pascalCase } from "@ng-openapi/shared";

export class ZodIndexGenerator {
    private project: Project;

    constructor(project: Project) {
        this.project = project;
    }

    generateIndex(outputRoot: string): void {
        const validatorsDir = path.join(outputRoot, "validators");
        const indexPath = path.join(validatorsDir, "index.ts");
        const sourceFile = this.project.createSourceFile(indexPath, "", { overwrite: true });

        sourceFile.insertText(0, this.generateHeaderComment());

        // Get all validator files
        const validatorFiles = fs
            .readdirSync(validatorsDir)
            .filter((file) => file.endsWith(".validator.ts"))
            .map((file) => file.replace(".validator.ts", ""));

        // Add exports
        validatorFiles.forEach((fileName) => {
            sourceFile.addExportDeclaration({
                namedExports: ["*"],
                moduleSpecifier: `./${fileName}.validator`,
            });
        });

        sourceFile.formatText();
        sourceFile.saveSync();
    }

    private generateHeaderComment(): string {
        return `/**
 * Validators Index
 * Generated by ng-openapi
 * Do not edit manually
 */\n\n`;
    }
}