const disableLinting = `/* @ts-nocheck */\n/* eslint-disable */\n/* @noformat */\n/* @formatter:off */\n`;
const authorComment = `/**\n* Generated by ng-openapi\n`;
const defaultHeaderComment = disableLinting + authorComment;
export const TYPE_GENERATOR_HEADER_COMMENT =
    defaultHeaderComment +
    `* Generated TypeScript interfaces from Swagger specification\n* Do not edit this file manually\n*/\n`;
export const SERVICE_INDEX_GENERATOR_HEADER_COMMENT =
    defaultHeaderComment + `* Generated service exports\n* Do not edit this file manually\n*/\n`;
export const SERVICE_GENERATOR_HEADER_COMMENT = (controllerName: string) =>
    defaultHeaderComment +
    `* Generated Angular service for ${controllerName} controller\n* Do not edit this file manually\n*/\n`;
export const MAIN_INDEX_GENERATOR_HEADER_COMMENT =
    defaultHeaderComment + `* Entrypoint for the client\n* Do not edit this file manually\n*/\n`;
export const PROVIDER_GENERATOR_HEADER_COMMENT =
    defaultHeaderComment + `* Generated provider functions for easy setup\n* Do not edit this file manually\n*/\n`;
